### ISSUE TITLE
-wCOMM fail to produce fully

### ISSUE THREAD

**Issue by J-P-** [squell/id3#1]
Thanks very much for your efforts and program. 

I am having a little issue with -wCOMM,

id3 -2 -wTXXX:descr value filepsec     >> works as expected
id3 -2 -wCOMM value filepsec     >> works as expected, but no language
id3 -2 -wCOMM:descr value filepsec     >> fails, as not delimited properly in the metadata header

**Comment by squell** [comment]
Thanks for the bug report. The empty/invalid language specifier ("xxx") seems to missing in the third case.

**Comment by squell** [comment]
(Fixed)

**Comment by J-P-** [comment]
Thanks
