### ISSUE TITLE
How to replace the str in the Tags with Python?

### ISSUE THREAD

**Issue by pendave** [squell/id3#10]
I wonder if I can use some defined function in Python to replace the strings?

How could I firstly read out the Tags strings as variable to be used in Python?

like rep(string):
`command = ["D:\****\id3-080w\id3.exe","-2","-c","www.****.com","-a",rep(%a),"-l",rep(%l),"-g",rep(%g),i]
`
`subprocess.call(command)`

But this reports syntax error in Python.

Thanks

**Comment by squell** [comment]
This works for me:

``` Python
import subprocess

def id3value(fmt, filename):
        command = ["./id3","-q",fmt,filename]
        return subprocess.check_output(command).rstrip()

print "The tag value is '%s'" % id3value("%g", "mp3/5sec.mp3")
```

You are better off finding a proper library for Python, though.
