### ISSUE TITLE
publisher tag

### ISSUE THREAD

**Issue by darkworks** [squell/id3#11]
can we add publisher tag , and composer etc like when we click on mp3 file in windows it have a lot of tags

**Comment by squell** [comment]
A publisher in ID3v2 is the `TPUB` frame, the composer is the `TCOM` frame; you can write those with:

`id3 -2 -wTPUB publisher -wTCOM composer file.mp3`

For more information on all the possible extra fields, see the id3v2 documentation at http://id3.org/d3v2.3.0; all frames that start with a T (text fields) or W (URLs) can be written by id3 (and some other frames as well -- which ones exactly is documented in the readme/manpage).
