### ISSUE TITLE
Potential confusion with that other program

### ISSUE THREAD

**Issue by squell** [squell/id3#14]
Recently, Peter Pentchev adopted the ancient Robert Woodcock _id3_ program and started maintaining it again, bumping the version number from 0.15 to 1.0: https://devel.ringlet.net/audio/id3/.

This presents a dilemma, since there's now "id3 1.0" and "id3 0.80".

Possible solutions:

1. Inflate the version numbering; e.g. go from "v0.80" to "v5.00", or something.

2. Change the /branding/ subtly (e.g. change the name of this repo, tarballs, website titles)

**Comment by Sp1l** [comment]
Can't imagine why someone would prefer the other `id3` over your implementation... Only id3v1 doesn't cut it nowadays...

**Comment by squell** [comment]
Leaving as is.
