### ISSUE TITLE
How can I delete ID3v1 Comment tag with this software?

### ISSUE THREAD

**Issue by shillshocked** [squell/id3#17]
I haven't quite figured out the syntax yet. I just want to delete ID3v1 Comment, nothing else.

**Comment by Sp1l** [comment]
`id3 -1d *.mp3`

**Comment by squell** [comment]
The previous answer deletes the entire ID3v1 tag, if you only want to remove the ID3v1 comment but keep the rest of the ID3v1 tag, you can use `id3 -1 -c "" file.mp3`.

**Comment by Sirove** [comment]
> I haven't quite figured out the syntax yet. I just want to delete ID3v1 Comment, nothing else.

I came here for the exact same question but

> The previous answer deletes the entire ID3v1 tag, if you only want to remove the ID3v1 comment but keep the rest of the ID3v1 tag, you can use `id3 -1 -c "" file.mp3`.

unfortunately doesn't work! No syntax error, simply not working... :(

**Comment by squell** [comment]
It always helps if I can reproduce potential problems, so in a case like that, try to produce a minimal testcase that doesn't work for you (e..g a small file with no copyright issues), and mail it to me. It also helps if I know what system you are using!
