### ISSUE TITLE
Tagging produces "trailing garbage"

### ISSUE THREAD

**Issue by Sp1l** [squell/id3#18]
After many years as a very happy user of id3 I've run into a small issue. Tagging produces trailing garbage, probably since upgrading to FreeBSD 11.1

```
FreeBSD 11.1-p1 amd64
audio/id3mtag 0.80 from ports
```

Tried to create something that can be reproduced, but failed sofar.

**Comment by squell** [comment]
Can you give some hint as to what type of commandline operations produce this result?

**Comment by Sp1l** [comment]
Files converted with lame 3.97
Check with mp3ck -v before tagging (no errors)
`id3 -M2 -a "Some Artist" -l "Some Album" -y 2017 -g Pop -n "%1" -t "%2" "*-*.mp3"`
check with mp3ck -v after tagging
`01-Some Song.mp3: trailing junk at byte offset 0x85c374`
Not consistent though. Looking a way to reproduce

**Comment by Sp1l** [comment]
Not seen anything like this recently. Currently running FreeBSD 13.0 amd64
