### ISSUE TITLE
tab-completion

### ISSUE THREAD

**Issue by r8b7xy** [squell/id3#2]
I can't tab complete 'id3 "song"'. After hitting tab terminal shows only possible options.

**Comment by J-P-** [comment]
What do you mean by "tab?"

Typing: id3 "filename"  then enter in a console should return the following:
  a) the file name
  b) the id3 format version
  c) 6 metadata frames (id: value). They are Title, Artist, Album, Track#, Year and Genre

To return other values, the -q %{frame id} parameter is necessary. For example:
  id3 -2 -q %{IPLS} "filename"     gives "involved persons" from an mp3 file with id3v2.3 metadata

**Comment by r8b7xy** [comment]
Let me show you the screencast [here](https://youtu.be/2Md0i_lD6f8)
When I press tab right afterwards the 'id3' command I'd love to see possible mp3s to check.

**Comment by squell** [comment]
Agreed. I added a (simple) bash auto-completion script which does this. (./bash/complete); it will be installed when running 'make bash_completion'.
