### ISSUE TITLE
Make dot (.) replacement by underscore (_) optional

### ISSUE THREAD

**Issue by dllud** [squell/id3#21]
I am renaming files with the command `id3 -2 -f "%n. %a - %t.mp3" test.mp3` and expected the result to be something like `01. artist - title.mp3`. However the result is `01_ artist - title.mp3`, with the dot (`.`) substituted for an underscore (`_`).
I have tried to escape the dot with a backslash (`%n\. %a - %t.mp3`) to no avail. I always get an underscore on the filename.
Which is the proper way to get a dot (`.`) on the filename?

**Comment by dllud** [comment]
Answering my own question. The culprit code is at [setfname.cpp:71](https://github.com/squell/id3/blob/51e738e7575c54fd7fdd54c931a155b25c3f2d30/setfname.cpp#L71). There is no way to avoid this behaviour without deleting those lines and recompiling. 

@squell Would you accept a PR that makes this optional?

**Comment by squell** [comment]
PR's: shoot them first, ask questions later. I have extremely limited time to devote to this project so a PR is always easier to merge!

This particular code was contributed by nplanel (in f67d862f), for vfat compatibility. I don't really like adding switches for such things, maybe it would be better to first try and rename with the dot present, and then if the FS complains use a more conservative filename.

**Comment by squell** [comment]
Having looked into this, I don't really see the need for forbid multiple dots; the original code didn't forbid it and was originally developed using DJGPP.

**Comment by dllud** [comment]
Thanks a lot for having a go at it! I've just compiled and tested at commit a899eac and it now works as I expected.

Shame on me for not submitting a PR right away. I even had a patch file ready, that I was applying to my build.
