### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by JamieSlome** [squell/id3#25]
Hello,

We recently received a potential vulnerability disclosure in your repository. I tried finding a contactable e-mail or a security process to follow, but couldn't find this.

If you would like me to send the details over to a preferred e-mail address, let me know - I will be happy to facilitate this for you.

Otherwise, you can view the vulnerability disclosure [here](https://huntr.dev/bounties/1-other-squell/id3/) - reported by @geeknik.

It is private and only visible to the maintainers and discloser.

Let me know if you have any questions!

-- Jamie from huntr.dev

**Comment by squell** [comment]
Assuming I found the same problem: the ID3v2 tag is semantically checked upon reading, and its end is marked with a sentinel value, but the size-information (not allocated in this sentinel object) will be accessed even for a sentinel value, in https://github.com/squell/id3/blob/f8d5178165fea1adc8204dbb6546493e25c07abf/id3v2.c#L421
This can go out-of-heap-bounds if a tag has less than 4 bytes of padding.

I would say the severity of this is "low": as long as the program doesn't segfault, https://github.com/squell/id3/blob/f8d5178165fea1adc8204dbb6546493e25c07abf/id3v2.c#L445 will indicate that no correct frame has been read, and the (garbage) size information parsed by ul4() will be discarded. Still, it would be more appropriate if ID3_frame just is a no-op if sees the end-of-tag sentinel, which is an easy fix.
