### ISSUE TITLE
Proper attribution

### ISSUE THREAD

**Issue by miniBill** [squell/id3#30]
I'm collecting test files for my ID3 parser, and while the license of your repository allows me to simply copy them by providing proper attribution, I wanted to make sure that you're ok with it.

The files are at https://github.com/miniBill/id3-test-files/tree/main/squell/id3

**Comment by squell** [comment]
Thanks for checking and taking care of proper attribution. I wouldn't have thought a single test file would be that interesting for someone else, but of course this falls both within the letter and the spirit of the BSD license. :-)

**Comment by miniBill** [comment]
Good :)
