### ISSUE TITLE
id3 0.80 can't find file with brackets in name

### ISSUE THREAD

**Issue by WonderRat** [squell/id3#7]
```
E:\>for %m in (*.mp3) do id3 -v "%m"

E:\>id3 -v "[test].mp3"
id3: no files matching [test].mp3

E:\>id3 -v "[].mp3"
id3: no files matching [].mp3
```

**Comment by squell** [comment]
Thanks. Introduced in commit 56f6ef4079b120049fc1c67f3c19448dc15eb863.

Out of curiousity: if a directory contains both 't.mp3' and '[test].mp3', which file do you think the wildcard '[test].mp3' should match? (bash selects "t.mp3"; _Take Command_ selects "[test].mp3".)

**Comment by WonderRat** [comment]
If you want to support such wildcards, then t.mp3 and need an option to disable wildcards.

**Comment by DmitriK** [comment]
+1. I'm using GNU parallel to invoke id3 which calls it with one file at a time. The internal pattern matching is making it impossible to modify files with brackets in them. I agree that there needs to be a way of ignoring wildcards and treating the filename as verbatim.

**Comment by squell** [comment]
1. Fixed the bug which made id3 ignore files with brackets in them (which was introduced in 56f6ef4).
2. Added the `-X` / `--no-glob` option which disables wildcard handling altogether

Both changes are now in master: https://github.com/squell/id3/compare/53c538f4db...d257053d42

Thanks for the bug reports and helpful comments!

**Comment by squell** [comment]
My fix is incomplete, as --no-glob is ignored for a simple `id3` / `id3 -v`. I should probably also add escaping to allow globbing to be used in combination with files which have brackets in them.

**Comment by hejops** [comment]
Has any progress been made on this bug?

**Comment by squell** [comment]
- [x] `--no-glob` should also affect `id3 -v` or plain `id3`
- [x] `\` can be used to escape `[`, `?` and `*`
